default_name: Гость
greetings: ', добрый день! Ответьте, пожалуйста, правдиво на следующие вопросы, чтобы узнать Ваш уровень коммуникабельности.'
answer_type: 'Для ответа введите:'
anwer_yes: да
anwer_no: нет
anwer_sometimes: иногда
result_message: 'Ваш результат в баллах -'